### ISSUE TITLE
Orthogonality

### ISSUE THREAD

**Issue by JacquesCarette** [Zistack/program-modeling-language#5]
In reference to [Orthogonality](https://github.com/Zistack/program-modeling-language/wiki/Orthogonality), I think you should read Felleisen's [On the Expressive Power  of Programming Languages](https://homepage.cs.uiowa.edu/~jgmorrs/eecs762f19/papers/felleisen.pdf). I think some of the definitions you're seeking are there, in some form.

**Comment by Zistack** [comment]
Well, that was an interesting read, for sure.  A near-miss, though.

Basically, aside from the notion of what it means for a language to be a sub-language of another, the ideas in the paper are merely closely related to what I am trying to present.  Not only is my definition of a programming language fundamentally different from theirs (theirs is still too syntactically/computationally focused), but also the relationships between programming languages that they are trying to define (while certainly interesting and useful), are not quite the relationships that I use to define orthogonality.

**Comment by JacquesCarette** [comment]
I think the main point for me to send this to you is to establish vocabulary.  For you to best communicate your ideas to others, it is best to start from established concepts, and then modify/adapt/expand them as needed.

For example, being able to contrast Felleisen's precise definitions with yours would be helpful to capture what your intent is.
