### ISSUE TITLE
Related work?

### ISSUE THREAD

**Issue by JacquesCarette** [Zistack/program-modeling-language#8]
[Mining Idioms in the Wild](https://arxiv.org/abs/2107.06402).

It is of course easy to see all the differences in the ideas, it is more interesting to see the points in common. You speak in terms of traces, they do it terms of dataflow, but the "source of the information" is the same. And, by the time you get to the ASTs contained in the paper, you're not quite language-independent, but it is a solid ½-way there.

**Comment by Zistack** [comment]
Yes, the core idea of canonizing the semantic meaning of constructions in a language so as to identify common patterns is definitely related to what I'm doing.  My perspective on the meaning of a program is in many ways analogous to the dataflow perspective as well.

**Comment by JacquesCarette** [comment]
Ok good. This means that, although I am not understanding the details of what you're doing, I am starting to understand the big picture.  Closing this, as the purpose of the issue has been achieved.
